name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: windows-2022

    env:
      PROJECT_PATH: WpfApp1
      DIST_PATH: Dist
      ARCHIVE_NAME: WpfApp1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: .NET Publish
        run: dotnet publish -c Release ${{ env.PROJECT_PATH }} -o ${{ env.DIST_PATH }}

      - name: Create archive
        run: Compress-Archive -Path ${{ env.DIST_PATH }}\* -DestinationPath ${{ env.DIST_PATH }}\${{ env.ARCHIVE_NAME }}.zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.DIST_PATH }}\${{ env.ARCHIVE_NAME }}.zip
          asset_name: ${{ env.ARCHIVE_NAME }}.zip
          asset_content_type: application/zip  